### ISSUE TITLE
Haikunator is not a constructor

### ISSUE THREAD

**Issue by tankovicsg** [Atrox/haikunatorjs#41]
There's a problem is version 2.1.0

Code: (copy/paste from readme)
```
var Haikunator = require('haikunator')

// Instantiate Haikunator without options
var haikunator = new Haikunator()

// default usage
console.log(haikunator.haikunate());
```
Error:
```
tankovics-g-mbpro:temp gtankovics$ node haikunator-test.js 
/Users/gtankovics/temp/haikunator-test.js:4
var haikunator = new Haikunator()
                 ^

TypeError: Haikunator is not a constructor
    at Object.<anonymous> (/Users/gtankovics/temp/haikunator-test.js:4:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

I've tested with node v8.15.1 and v10.15.3

**Comment by Atrox** [comment]
I just reproduces this, I'm sorry. I'll publish a fixed `2.1.1` ASAP. Thanks for opening up a issue.
